### ISSUE TITLE
compareSync value is false

### ISSUE THREAD

**Issue by jonathanhendra** [Tariqu/REST_API_WITH_MYSQL#1]
i have trouble in this code, i always got false value of compareSync. help me to solved this
login: (req, res) => {
        const body = req.body;
        getUserByUserEmail(body.email, (err, results) => {
            if (err) {
                console.log(err);
            }
            if (!results) {
                return res.json({
                    success: 0,
                    data: "Invalid email or password"
                });
            }

            // const salt = genSaltSync(10);
            // body.password = hashSync(body.password, salt);

            const result = compareSync(body.password, results.password);
            console.log(results); // here i try to see log console

            if (result) {
                results.password = undefined;
                const jsontoken = sign({ result: results }, process.env.JWT_KEY, {
                    expiresIn: "1h"
                });
                return res.json({
                    success: 1,
                    message: "login successfully",
                    token: jsontoken
                });
            } else {
                return res.json({
                    success: 0,
                    data: "Invalid email or password"
                });
            }
        });
    },

**Comment by Tariqu** [comment]
This happens when your password doesn't match. The common mistake people do here is they take the password field in database as varchar (like varchar(20)), the encrypted password length was grater then 20 as eg. so my default rest character database ignored and store only 20 char in password field and when you retrieve and compare you are getting false because its not matching with actual encrypted password. Hope you are getting what I am try to convince.

so either increase password field length or make it text field so that we can store any length character
